# Generated by Django 2.2 on 2022-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeduzaRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField()),
                ('sound', models.FileField(default='', max_length=100)),
            ],
            options={'ordering': ['-datetime']},
            
        ),
    ]