# Generated by Django 2.2 on 2022-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meduzarecord',
            name='content',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='meduzarecord',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='meduzarecord',
            name='sound',
            field=models.CharField(default='', max_length=100, verbose_name='Имя соответствующего mp3-файла'),
        ),
        migrations.AlterField(
            model_name='meduzarecord',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='meduzarecord',
            name='url',
            field=models.SlugField(unique=True, verbose_name='url новости'),
        ),
    ]
